### ISSUE TITLE
Update Ui.png, McScheduler description and acknowledgements on website landing page

### ISSUE THREAD

**Issue by wakululuu** [AY2021S1-CS2103-F10-4/tp#210]
<img width="1364" alt="Screenshot 2020-11-06 at 10 17 06 AM" src="https://user-images.githubusercontent.com/28750239/98318337-61ae0d80-2019-11eb-8683-e7d14c27e278.png">

**Comment by tnsyn** [comment]
Fix the grammar mistake in the description ("for McDonald’s Shift Managers _to managing_ shift scheduling")
